spring:
   application:
      version: ^project.version^
      name: ^project.name^
   datasource:
      url: jdbc:postgresql://${APP_DB_HOST:localhost}:${APP_DB_PORT:5432}/${APP_DB_NAME:postgres}
      username: ${APP_DB_USERNAME:dummy}
      password: ${APP_DB_PASSWORD:dummy}
      driver-class-name: org.postgresql.Driver
      testOnBorrow: true
      validationQuery: SELECT 1
      validationInterval: 30000
      hikari:
         minimum-idle: ${APP_DB_MINIMUM_IDEL_CONNECTIONS:10}
         maximum-pool-size: ${APP_DB_MAX_CONNECTION_SIZE:50}
         idle-timeout: 10000
         connection-timeout: 60000
   jpa:
      open-in-view: false
      show-sql: false
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate.ddl-auto: ${HIBERNATE_DDL_AUTO:update}
      properties:
         hibernate.default_schema: ${APP_DB_SCHEMA:blockly}
         hibernate.temp.use_jdbc_metadata_defaults: false
         hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
         hibernate.naming-strategy: org.hibernate.cfg.DefaultNamingStrategy

spring.servlet.multipart:
   maxFileSize: ${MAX_UPLOAD_FILE_SIZE:200MB}
   maxRequestSize: ${MAX_REQUEST_SIZE:201MB}

spring.data.web.pageable:
   max-page-size: 1000
   default-page-size: 50

server:
   port: ${CONFIG_SERVER_PORT:8080}
   servlet:
      context-path: ${SERVLET_CONTEXT_PATH:/blockly-backend}

logging:
   level:
      root: INFO
      org.teapotech: DEBUG
     
